str = 'TCAGCAGCAACTGCGACGGTCTGTCTTGACGCATCTAACAAGATCGTATTACCATAGCTCTAGACATTAACTGGTAAGTAACCGGTTAAGAGGTCGAGCCGCCCCTGCCTCCAGTCCGATTAAGGCGTGATTTTCTCCGAGTCTGCGTAGCCAAGTGGGAAGAGGGGAGGCCCTCCGGAGCCCGAGTGATCAGCGGAGGCCACTGTAATGTATGACCAGGTAAGTCGGTTTTACTGCCTCTACTAGCTTGGGCGTCGAGCAAGTAGCGTCGAGGGTTGTAATTGTTGCAGTTCCTTATACTGACGAGTGGTACAGATTGCACGCATTTAGATCCTTTAGAGTGCGGTACCCAGTCTAGCAATGCATTGGGGTGTCCGTTAACGCATCCGACCCTGTAGTACCCGGGGTGGTCACTCAAATGTCTATAGTATGAGAATACGTTGCACGTGTTTCGATCTTAGGAGAAAGGTTCTGCTATGTACGAGTCGGTGTGGTGACCCAAGTTATTGGCAGTGTGAGATGTTCACTCGTTTCATACACGATCCGTCTCTACCCTTGATCCGTGACTCAAAGCATTATCAAATACCACGCGTGTTGGGTGGGTAGTCTCTAAGTTTTTGAGGATGGGTTGCTAGACGTCTGAGAACACACCTCCTATTCAACTCGGGAGTAATACGCACCGTTAGAATGATCGGAAAAACCTGTATGGATCCCCTCCTATGCAGTTCGCTGGGGTTGGCCCACGTTGGGAGGTATCAGGATTGTGACCCCAGTGCCTGGCTAGACGATACAAGAACTCGGTCGCGGCAATGTAAGATGAGGTTTATGATGGGGGCCGCTCGAGTCAACAGGCCCTATCCTGCGTCGAATTGCAGGGGACATTCTACTCTCAGACGCATCCGAATCGCTCATTTCATTCAGGCGAGATTAAAGCCAAATCGCGAGGATCTATTAGGCGACAACGAGTGCGCGGGTGGCTAATAGA'
Acount = 0
Ccount = 0
Gcount = 0
Tcount = 0

for i in str:
    if i == 'A':
        Acount += 1
    elif i == 'C':
        Ccount += 1
    elif i == 'G':
        Gcount += 1
    elif i == 'T':
        Tcount += 1

print(Acount)
print(Ccount)
print(Gcount)
print(Tcount)